//
//  ServerList.swift
//  WoW PvP Armory
//
//  Created by Joseph Gilmore on 8/23/22.
//

import Foundation

class ServerList {
    
    static let serverListNA = [
        "Aerie Peak",
        "Aggramar",
        "Alexstrasza",
        "Alleria",
        "Alterac Mountains",
        "Area 52",
        "Argent Dawn",
        "Arthas",
        "Azralon",
        "Azuremyst",
        "Barthilas",
        "Blackhand",
        "Bladefist",
        "Bleeding Hollow",
        "Bloodhoof",
        "Bonechewer",
        "Burning Blade",
        "Burning Legion",
        "Cho'gall",
        "Crushridge",
        "Dalaran",
        "Darkspear",
        "Deathwing",
        "Doomhammer",
        "Draenor",
        "Dragonblight",
        "Drakkari",
        "Earthen Ring",
        "Emerald Dream",
        "Eredar",
        "Feathermoon",
        "Gallywix",
        "Goldrinn",
        "Greymane",
        "Hyjal",
        "Illidan",
        "Jubei'Thos",
        "Kel'Thuzad",
        "Khaz Modan",
        "Khaz'goroth",
        "Kil'Jaeden",
        "Kilrogg",
        "Kirin Tor",
        "Lightbringer",
        "Llane",
        "Maelstrom",
        "Magtheridon",
        "Mal'Ganis",
        "Moon Guard",
        "Mug'thol",
        "Nagrand",
        "Nemesis",
        "Ner'zhul",
        "Proudmoore",
        "Quel'Thalas",
        "Ragnaros",
        "Ravencrest",
        "Rexxar",
        "Sargeras",
        "Sen'Jin",
        "Shadow Council",
        "Shadowmoon",
        "Shandris",
        "Shattered Hand",
        "Shu'halo",
        "Silver Hand",
        "Silvermoon",
        "Spirestone",
        "Stormrage",
        "Stormreaver",
        "Suramar",
        "Thrall",
        "Thunderlord",
        "Tichondrius",
        "Trollbane",
        "Turalyon",
        "Uther",
        "Vek'nilash",
        "Whisperwind",
        "Wyrmrest Accord",
        "Ysera",
        "Zul'jin",
        "Zuluhed"
    ]
}
